In [4]:
import numpy as np
import pandas as pd

In [5]:
from google.colab import files
uploaded = files.upload()

Saving sonar_data.csv to sonar_data (1).csv

In [6]:
df = pd.read_csv('sonar_data.csv',header=None) #header (default) = 0.
df.head()

,0,1,2,3,4,5,6,7,8,9,...,51,52,53,54,55,56,57,58,59,60
0,0.0200,0.0371,0.0428,0.0207,0.0954,0.0986,0.1539,0.1601,0.3109,0.2111,...,0.0027,0.0065,0.0159,0.0072,0.0167,0.0180,0.0084,0.0090,0.0032,R
1,0.0453,0.0523,0.0843,0.0689,0.1183,0.2583,0.2156,0.3481,0.3337,0.2872,...,0.0084,0.0089,0.0048,0.0094,0.0191,0.0140,0.0049,0.0052,0.0044,R
2,0.0262,0.0582,0.1099,0.1083,0.0974,0.2280,0.2431,0.3771,0.5598,0.6194,...,0.0232,0.0166,0.0095,0.0180,0.0244,0.0316,0.0164,0.0095,0.0078,R
3,0.0100,0.0171,0.0623,0.0205,0.0205,0.0368,0.1098,0.1276,0.0598,0.1264,...,0.0121,0.0036,0.0150,0.0085,0.0073,0.0050,0.0044,0.0040,0.0117,R
4,0.0762,0.0666,0.0481,0.0394,0.0590,0.0649,0.1209,0.2467,0.3564,0.4459,...,0.0031,0.0054,0.0105,0.0110,0.0015,0.0072,0.0048,0.0107,0.0094,R

In [7]:
df.shape

(208, 61)

In [8]:
df[60].value_counts()

60
M    111
R     97
Name: count, dtype: int64

In [9]:
X = df.drop(columns=60,axis=1)  #axis =1 column,axis=0 rows.
y = df[60]

In [10]:
train_size =0.7
sample_rows = X.shape[0]
rows = np.random.permutation(sample_rows)
n = int(train_size*sample_rows)
test_idx = rows[n:]
train_idx = rows[:n]

In [11]:
X_train =X.iloc[train_idx]#iloc gives permision to select rows and column, .iloc[selected_row,sel_col]  we can select rows location by slicing.
X_test =X.iloc[test_idx]
y_train =y.iloc[train_idx]
y_test =y.iloc[test_idx]

In [12]:
def sigmoid(z):
  return 1/(1+np.exp(-z))

def loss(y,y_hat):
  m=y.shape[0] #no. of sample example.
  return (-1/m)* np.sum(y*np.log(y_hat+1e-9)+(1-y)*np.log(1-y_hat+1e-9))

In [13]:
a,b=X.shape
W = np.zeros((b,1))
b=0

def train(X,y,lr=0.001,epochs=3000):

  for i in range(epochs):
    z=np.dot(X,W)+b
    y_hat = sigmoid(z)

    dw = (1/a) * np.dot(X.T,(y_hat-y))
    db = (1/a) * np.sum(y_hat - y)

    W -= lr * dw
    b -= lr * db

    if i%200 ==0:
      print(f"Epoch {i},Loss:{loss(y,y_hat):.4f}")
      # f: is formatting string(f-string)
      # which allows variable in string.

    return W,b

In [14]:
def predict(X,W,b):
  probability = sigmoid(np.dot(X,W)+b)
  return (probability>=0.5).astype(int)#astype int convert True and False to 1 and 0(boolean).